[template]
src = "ci-docker-compose.tmpl"
dest = "/etc/confd/output/docker-compose.yml"
keys = [
"/services/myci/project_config_dir",
"/services/datagerrit/image",
"/services/datagerrit/name",
"/services/datajenkins/image",
"/services/datajenkins/name",
"/services/pggerrit/image",
"/services/pggerrit/name",
"/services/pggerrit/postgres_user",
"/services/pggerrit/postgres_password",
"/services/pggerrit/postgres_db",
"/services/gerrit/image",
"/services/gerrit/name",
"/services/gerrit/weburl",
"/services/gerrit/httpd_listenurl",
"/services/gerrit/database_type",
"/services/gerrit/auth_type",
"/services/gerrit/ldap_server",
"/services/gerrit/ldap_accountbase",
"/services/jenkins/image",
"/services/jenkins/name",
"/services/jenkins/opts",
"/services/pgredmine/image",
"/services/pgredmine/name",
"/services/pgredmine/postgres_user",
"/services/pgredmine/postgres_password",
"/services/pgredmine/postgres_db",
"/services/redmine/image",
"/services/redmine/name",
"/services/redmine/db_name",
"/services/redmine/db_user",
"/services/redmine/db_pass",
"/services/redmine/relative_url_root",
"/services/redmine/fetch_commits",
"/services/nginxproxy/image",
"/services/nginxproxy/name",
"/services/nginxproxy/proxy_mapping",
]
